#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/tobimune_theme.sh"
source "$SCRIPT_DIR/accent_color.sh"

usage() {
    cat <<'EOF'
Usage: gen_style.sh [ACCENT] [FONT] [SIZE]
Generate theme files for the desktop environment.

Options:
    -a, --accent HEX    Set the accent color
    -f, --font NAME     Set the font family
    -s, --size N        Set the font size in pixels
    -h, --help          Show this help message
EOF
}

[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && { usage; exit 0; }

ACCENT_PROVIDED=false
SIZE_PROVIDED=false

if [[ "${1-}" != "" && "${1-}" != -* ]]; then ACCENT_COLOR="$1"; ACCENT_PROVIDED=true; shift; fi
if [[ "${1-}" != "" && "${1-}" != -* ]]; then FONT_FAMILY="$1"; shift; fi
if [[ "${1-}" != "" && "${1-}" != -* ]]; then FONT_SIZE="$1"; SIZE_PROVIDED=true; shift; fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --accent|-a) ACCENT_COLOR="${2:?missing value for --accent}"; ACCENT_PROVIDED=true; shift 2 ;;
        --font|-f) FONT_FAMILY="${2:?missing value for --font}"; shift 2 ;;
        --size|-s) FONT_SIZE="${2:?missing value for --size}"; SIZE_PROVIDED=true; shift 2 ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
done

if [[ "$ACCENT_PROVIDED" == true ]]; then
    ACCENT_COLOR="$(printf '%s' "$ACCENT_COLOR" | tr -cd '#0-9a-fA-F')"
    [[ "$ACCENT_COLOR" =~ ^#[0-9a-fA-F]{6}$ ]] || ACCENT_COLOR="$THEME_DEFAULT_ACCENT"

    validated_accent="$(accent_color_or_fallback "$ACCENT_COLOR")"
    if [[ "$validated_accent" == "$THEME_DEFAULT_ACCENT" && "${ACCENT_COLOR,,}" != "$THEME_DEFAULT_ACCENT" ]]; then
        notify-send "Color ${ACCENT_COLOR} is too dark" "Generating color failed" 2>/dev/null || true
        exit 1
    fi
    ACCENT_COLOR="$validated_accent"
fi

[[ "$SIZE_PROVIDED" == false || ( "$FONT_SIZE" =~ ^[0-9]+$ && "$FONT_SIZE" -gt 0 ) ]] || FONT_SIZE="$THEME_DEFAULT_SIZE"
[[ -n "$FONT_FAMILY" ]] || FONT_FAMILY="$THEME_DEFAULT_FONT"

theme_save_state

hex_to_rgba() {
    local hex="${1#\#}"
    printf 'rgba(%sff)\n' "${hex,,}"
}

hex_to_rgb() {
    local hex="${1#\#}"
    printf 'rgb(%d, %d, %d)\n' $((16#${hex:0:2})) $((16#${hex:2:2})) $((16#${hex:4:2}))
}

hex_to_0x() {
    printf '0x%sff\n' "${1#\#}"
}

hex_to_rgba_alpha() {
    local hex="${1#\#}" alpha="${2:-0.4}"
    printf 'rgba(%d, %d, %d, %s)\n' $((16#${hex:0:2})) $((16#${hex:2:2})) $((16#${hex:4:2})) "$alpha"
}

ACCENT_RGBA="$(hex_to_rgba "$ACCENT_COLOR")"
ACCENT_RGB="$(hex_to_rgb "$ACCENT_COLOR")"
ACCENT_0X="$(hex_to_0x "$ACCENT_COLOR")"

ACCENT_DIM_ALPHA="${ACCENT_DIM_ALPHA:-0.8}"
ACCENT_DIM="$(hex_to_rgba_alpha "$ACCENT_COLOR" "$ACCENT_DIM_ALPHA")"

render_colors() {
    cat > "$THEME_RENDER_DIR/colors.css" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
@define-color accent_color ${ACCENT_COLOR};
EOF
}

render_fonts() {
    cat > "$THEME_RENDER_DIR/fonts.css" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
* {
    font-family: "${FONT_FAMILY}";
    font-size: ${FONT_SIZE}px;
}
EOF
}

render_hyprland() {
    cat > "$THEME_RENDER_DIR/hyprland-style.conf" <<EOF
# Generated by ~/.local/bin/gen_style.sh
\$font_family = ${FONT_FAMILY}
\$font_size = ${FONT_SIZE}
\$accent_color = ${ACCENT_RGB}
EOF
    cat > "$THEME_RENDER_DIR/hyprland-style.lua" <<EOF
-- Generated by ~/.local/bin/gen_style.sh
return {
    font_family = "${FONT_FAMILY}",
    font_size = ${FONT_SIZE},
    border_color = "${ACCENT_RGBA}",
}
EOF
}

render_rofi() {
    cat > "$THEME_RENDER_DIR/rofi-style.rasi" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
* {
    accent: ${ACCENT_COLOR};
    accent-dim: ${ACCENT_DIM};
    font: "${FONT_FAMILY} ${FONT_SIZE}";
}
EOF
    cat > "$THEME_RENDER_DIR/rofi-wallpaper-select.rasi" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
* {
    font: "${FONT_FAMILY} 11";
}
EOF
}

render_kitty() {
    cat > "$THEME_RENDER_DIR/kitty-style.conf" <<EOF
# Generated by ~/.local/bin/gen_style.sh
font_family      family="${FONT_FAMILY}"
font_size        ${FONT_SIZE}
foreground ${ACCENT_COLOR}
color7 ${ACCENT_COLOR}
color15 ${ACCENT_COLOR}
EOF
}

render_btop() {
    mkdir -p "$THEME_BTOP_DIR"
    cat > "$THEME_BTOP_DIR/TobimuneBtop.theme" <<EOF
# Generated by ~/.local/bin/gen_style.sh
theme[main_bg]="#000000"
theme[main_fg]="#c0c0c0"
theme[title]="${ACCENT_COLOR}"
theme[hi_fg]="${ACCENT_COLOR}"
theme[selected_fg]="${ACCENT_COLOR}"
theme[proc_misc]="${ACCENT_COLOR}"
theme[cpu_box]="${ACCENT_COLOR}"
theme[mem_box]="${ACCENT_COLOR}"
theme[net_box]="${ACCENT_COLOR}"
theme[disk_box]="${ACCENT_COLOR}"
EOF
}

render_newtab() {
    cat > "$THEME_RENDER_DIR/newtab.css" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
:root {
    --accent_color: ${ACCENT_COLOR};
    --font_family: "${FONT_FAMILY}";
}
EOF
}

RENDERERS=(colors fonts hyprland rofi kitty btop newtab)
for renderer in "${RENDERERS[@]}"; do
    "render_${renderer}"
done

echo "Generated theme files in: $THEME_RENDER_DIR"
echo "ACCENT_COLOR=$ACCENT_COLOR"
echo "FONT_FAMILY=$FONT_FAMILY"
echo "FONT_SIZE=$FONT_SIZE"
