#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/haku_theme.sh"
source "$SCRIPT_DIR/accent_color.sh"

usage() {
    cat <<'EOF'
Usage: gen_style.sh [ACCENT] [FONT] [SIZE]
Generate theme files for the desktop environment.

Options:
    -a, --accent HEX    Set the accent color
    -f, --font NAME     Set the font family
    -s, --size N        Set the font size in pixels
    -h, --help          Show this help message
EOF
}

[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && { usage; exit 0; }

ACCENT_PROVIDED=false
SIZE_PROVIDED=false

if [[ "${1-}" != "" && "${1-}" != -* ]]; then ACCENT_COLOR="$1"; ACCENT_PROVIDED=true; shift; fi
if [[ "${1-}" != "" && "${1-}" != -* ]]; then FONT_FAMILY="$1"; shift; fi
if [[ "${1-}" != "" && "${1-}" != -* ]]; then FONT_SIZE="$1"; SIZE_PROVIDED=true; shift; fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --accent|-a) ACCENT_COLOR="${2:?missing value for --accent}"; ACCENT_PROVIDED=true; shift 2 ;;
        --font|-f) FONT_FAMILY="${2:?missing value for --font}"; shift 2 ;;
        --size|-s) FONT_SIZE="${2:?missing value for --size}"; SIZE_PROVIDED=true; shift 2 ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
done

if [[ "$ACCENT_PROVIDED" == true ]]; then
    ACCENT_COLOR="$(printf '%s' "$ACCENT_COLOR" | tr -cd '#0-9a-fA-F')"
    [[ "$ACCENT_COLOR" =~ ^#[0-9a-fA-F]{6}$ ]] || ACCENT_COLOR="$THEME_DEFAULT_ACCENT"

    validated_accent="$(accent_color_or_fallback "$ACCENT_COLOR")"
    if [[ "$validated_accent" == "$THEME_DEFAULT_ACCENT" && "${ACCENT_COLOR,,}" != "$THEME_DEFAULT_ACCENT" ]]; then
        notify-send "Color ${ACCENT_COLOR} is too dark" "Generating color failed" 2>/dev/null || true
        exit 1
    fi
    ACCENT_COLOR="$validated_accent"
fi

[[ "$SIZE_PROVIDED" == false || ( "$FONT_SIZE" =~ ^[0-9]+$ && "$FONT_SIZE" -gt 0 ) ]] || FONT_SIZE="$THEME_DEFAULT_SIZE"
[[ -n "$FONT_FAMILY" ]] || FONT_FAMILY="$THEME_DEFAULT_FONT"

theme_save_state

hex_to_rgba() {
    local hex="${1#\#}"
    printf 'rgba(%sff)\n' "${hex,,}"
}

hex_to_rgb() {
    local hex="${1#\#}"
    printf 'rgb(%d, %d, %d)\n' $((16#${hex:0:2})) $((16#${hex:2:2})) $((16#${hex:4:2}))
}

hex_to_0x() {
    printf '0x%sff\n' "${1#\#}"
}

hex_to_rgba_alpha() {
    local hex="${1#\#}" alpha="${2:-0.4}"
    printf 'rgba(%d, %d, %d, %s)\n' $((16#${hex:0:2})) $((16#${hex:2:2})) $((16#${hex:4:2})) "$alpha"
}

ACCENT_RGBA="$(hex_to_rgba "$ACCENT_COLOR")"
ACCENT_RGB="$(hex_to_rgb "$ACCENT_COLOR")"
ACCENT_0X="$(hex_to_0x "$ACCENT_COLOR")"

ACCENT_DIM_ALPHA="${ACCENT_DIM_ALPHA:-0.8}"
ACCENT_DIM="$(hex_to_rgba_alpha "$ACCENT_COLOR" "$ACCENT_DIM_ALPHA")"

render_colors() {
    cat > "$THEME_RENDER_DIR/colors.css" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
@define-color accent_color ${ACCENT_COLOR};
EOF
}

render_fonts() {
    cat > "$THEME_RENDER_DIR/fonts.css" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
* {
    font-family: "${FONT_FAMILY}";
    font-size: ${FONT_SIZE}px;
}
EOF
}

render_hyprland() {
    cat > "$THEME_RENDER_DIR/hyprland-style.conf" <<EOF
# Generated by ~/.local/bin/gen_style.sh
\$font_family = ${FONT_FAMILY}
\$font_size = ${FONT_SIZE}
\$accent_color = ${ACCENT_RGB}
EOF
    cat > "$THEME_RENDER_DIR/hyprland-style.lua" <<EOF
-- Generated by ~/.local/bin/gen_style.sh
return {
    font_family = "${FONT_FAMILY}",
    font_size = ${FONT_SIZE},
    border_color = "${ACCENT_RGBA}",
}
EOF
}

render_rofi() {
    cat > "$THEME_RENDER_DIR/rofi-style.rasi" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
* {
    accent: ${ACCENT_COLOR};
    accent-dim: ${ACCENT_DIM};
    font: "${FONT_FAMILY} ${FONT_SIZE}";
}
EOF
    cat > "$THEME_RENDER_DIR/rofi-wallpaper-select.rasi" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
* {
    font: "${FONT_FAMILY} 11";
}
EOF
}

render_kitty() {
    cat > "$THEME_RENDER_DIR/kitty-style.conf" <<EOF
# Generated by ~/.local/bin/gen_style.sh
font_family      family="${FONT_FAMILY}"
font_size        ${FONT_SIZE}
foreground ${ACCENT_COLOR}
color7 ${ACCENT_COLOR}
color15 ${ACCENT_COLOR}
EOF
}

render_btop() {
    mkdir -p "$THEME_BTOP_DIR"
    cat > "$THEME_BTOP_DIR/HakuBtop.theme" <<EOF
# Generated by ~/.local/bin/gen_style.sh
theme[main_bg]="#000000"
theme[main_fg]="#c0c0c0"
theme[title]="${ACCENT_COLOR}"
theme[hi_fg]="${ACCENT_COLOR}"
theme[selected_fg]="${ACCENT_COLOR}"
theme[proc_misc]="${ACCENT_COLOR}"
theme[cpu_box]="${ACCENT_COLOR}"
theme[mem_box]="${ACCENT_COLOR}"
theme[net_box]="${ACCENT_COLOR}"
theme[disk_box]="${ACCENT_COLOR}"
EOF
}

render_newtab() {
    cat > "$THEME_RENDER_DIR/newtab.css" <<EOF
/* Generated by ~/.local/bin/gen_style.sh */
:root {
    --accent_color: ${ACCENT_COLOR};
    --font_family: "${FONT_FAMILY}";
}
EOF
}

render_niri() {
    cat > "$THEME_RENDER_DIR/niri-style.kdl" <<EOF
// Generated by ~/.local/bin/gen_style.sh
layout {
    focus-ring {
        active-color "${ACCENT_COLOR}"
    }
}
EOF
}

render_mango() {
    cat > "$THEME_RENDER_DIR/mangowm-style.conf" <<EOF
# Generated by ~/.local/bin/gen_style.sh
focuscolor=${ACCENT_0X}
maximizescreencolor=${ACCENT_0X}
scratchpadcolor=${ACCENT_0X}
globalcolor=${ACCENT_0X}
overlaycolor=${ACCENT_0X}
EOF
}

render_labwc() {
    if [[ -f "$THEME_LABWC_OVERRIDE" ]]; then
        local theme_block
        theme_block="# BEGIN GENERATED THEME
window.active.border.color: ${ACCENT_COLOR}
window.inactive.border.color: #000000
window.active.label.text.color: ${ACCENT_COLOR}
window.inactive.label.text.color: ${ACCENT_COLOR}
window.active.button.unpressed.image.color: ${ACCENT_COLOR}
window.inactive.button.unpressed.image.color: ${ACCENT_COLOR}
menu.items.active.bg: ${ACCENT_COLOR}
menu.items.text.color: ${ACCENT_COLOR}
menu.items.active.bg.color: ${ACCENT_COLOR}
menu.title.bg.color: ${ACCENT_COLOR}
osd.border.color: ${ACCENT_COLOR}
osd.label.text.color: ${ACCENT_COLOR}
osd.window-switcher.style-classic.item.active.border.color: ${ACCENT_COLOR}
osd.window-switcher.style-thumbnail.item.active.border.color: ${ACCENT_COLOR}
# END GENERATED THEME"
        if grep -q "# BEGIN GENERATED THEME" "$THEME_LABWC_OVERRIDE"; then
            awk -v block="$theme_block" '/# BEGIN GENERATED THEME/ { print block; skip=1; next } /# END GENERATED THEME/ { skip=0; next } !skip { print }' \
                "$THEME_LABWC_OVERRIDE" > "${THEME_LABWC_OVERRIDE}.tmp" && cat "${THEME_LABWC_OVERRIDE}.tmp" > "$THEME_LABWC_OVERRIDE" && rm -f "${THEME_LABWC_OVERRIDE}.tmp"
        fi
    fi

    if [[ -f "$THEME_LABWC_RC" ]]; then
        local labwc_font_size=$((FONT_SIZE - 2))
        (( labwc_font_size < 8 )) && labwc_font_size=8
        export GEN_FONT_BLOCK="        <!-- BEGIN GENERATED FONTS -->
            <font place=\"ActiveWindow\"><name>${FONT_FAMILY}</name><size>${labwc_font_size}</size><slant>normal</slant><weight>normal</weight></font>
            <font place=\"InactiveWindow\"><name>${FONT_FAMILY}</name><size>${labwc_font_size}</size><slant>normal</slant><weight>normal</weight></font>
            <font place=\"MenuHeader\"><name>${FONT_FAMILY}</name><size>${labwc_font_size}</size><slant>normal</slant><weight>normal</weight></font>
            <font place=\"MenuItem\"><name>${FONT_FAMILY}</name><size>${labwc_font_size}</size><slant>normal</slant><weight>normal</weight></font>
            <font place=\"OnScreenDisplay\"><name>${FONT_FAMILY}</name><size>${labwc_font_size}</size><slant>normal</slant><weight>normal</weight></font>
            <!-- END GENERATED FONTS -->"
        if grep -q "<!-- BEGIN GENERATED FONTS -->" "$THEME_LABWC_RC"; then
            awk '/<!-- BEGIN GENERATED FONTS -->/ { print ENVIRON["GEN_FONT_BLOCK"]; skip=1; next } /<!-- END GENERATED FONTS -->/ { skip=0; next } !skip { print }' \
                "$THEME_LABWC_RC" > "${THEME_LABWC_RC}.tmp" && cat "${THEME_LABWC_RC}.tmp" > "$THEME_LABWC_RC" && rm -f "${THEME_LABWC_RC}.tmp"
        fi
    fi
}

RENDERERS=(colors fonts hyprland rofi kitty btop newtab niri mango labwc)
for renderer in "${RENDERERS[@]}"; do
    "render_${renderer}"
done

echo "Generated theme files in: $THEME_RENDER_DIR"
echo "ACCENT_COLOR=$ACCENT_COLOR"
echo "FONT_FAMILY=$FONT_FAMILY"
echo "FONT_SIZE=$FONT_SIZE"
