--      __  ___      _                           _____      
--     /  |/  /___ _(_)___     _________  ____  / __(_)___ _
--    / /|_/ / __ `/ / __ \   / ___/ __ \/ __ \/ /_/ / __ `/
--   / /  / / /_/ / / / / /  / /__/ /_/ / / / / __/ / /_/ / 
--  /_/  /_/\__,_/_/_/ /_/   \___/\____/_/ /_/_/ /_/\__, /  
--                                                 /____/   

-- DO NOT EDIT THIS FILE, EDIT ~/hakucfg/wm/hyprland-custom.lua INSTEAD

local style_dir = os.getenv("HOME") .. "/.local/state/hakuspace/theme/"
local ok, style = pcall(dofile, style_dir .. "hyprland-style.lua")
if not ok then
    style = { font_family = "monospace", font_size = 16, border_color = "rgba(ffffffff)" }
end

local font_family = style.font_family
local font_size = style.font_size
local border_color = style.border_color

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "1",
})

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 10,
        gaps_out = 16,

        border_size = 3,

        col = {
            active_border   = border_color, -- auto-generated by hyprland-style.lua
            --active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(ffffff00)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        snap = {
            enabled = true,
            window_gap = 0,
            monitor_gap = 0,
            border_overlap = false,
            respect_gaps = false,
        },
    },

    decoration = {
        rounding       = 12,
        rounding_power = 4,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 0.9,

        shadow = {
            enabled      = true,
            range        = 20,
            render_power = 6,
            offset       = { 2, 2 },
            color        = "rgba(000000cc)",
        },

        blur = {
            enabled   = true,
            size      = 10,
            passes    = 3,
            vibrancy  = 2,
            contrast  = 1.4,
            noise     = 0.05,
            special   = false,
            input_methods = true,
        },
    },

    animations = {
        enabled = true,
    },
})


----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        disable_autoreload = false,
        middle_click_paste = true,
        force_default_wallpaper = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo
        font_family = font_family,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
    cursor = {
        no_warps = true,
        hide_on_key_press = true,
    }
})

hl.gesture({
    fingers = 3,
    direction = "vertical",
    action = "workspace"
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "scroll_move"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})
