--      ____        __   
--     / __ \__  __/ /__ 
--    / /_/ / / / / / _ \
--   / _, _/ /_/ / /  __/
--  /_/ |_|\__,_/_/\___/ 
--                       

-- DO NOT EDIT THIS FILE, EDIT ~/suzaku/wm/hyprland-custom.lua INSTEAD

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Set workspaces to be persistent, they are not destroyed when empty
hl.workspace_rule({ workspace = "1", persistent = true })
hl.workspace_rule({ workspace = "2", persistent = true })

suppressMaximizeRule = hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

fixXwaylandDrags = hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Hyprland-run windowrule
hyprlandRunRule = hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- VS Code in special workspace
codeSpecialWorkspace = hl.window_rule({
    name  = "code-scratchpad",
    match = { class = "code|com.microsoft.VSCode" },

    workspace = "special:magic",
})

-- Set border color to red if window is fullscreen
fullscreenBorder = hl.window_rule({
    name  = "fullscreen-border-color",
    match        = { fullscreen = true },

    border_color = "rgb(FF0000) rgb(880808)",
})


--------------------------------
------- SCROLLING LAYOUT -------
--------------------------------

fullWidth_ScrollingLayout = hl.window_rule({
    name = "full_width_scrolling",
    match = { class = "code|com.microsoft.VSCode|app.zen_browser.zen|zen.*|discord|firefox|google-chrome|jetbrains.*" },

    scrolling_width = 1.0
})

specificWidth_ScrollingLayout = hl.window_rule({
    name = "specific_width_scrolling",
    match = { class = "thunar|Thunar" },

    scrolling_width = 0.6
})

--------------------------------
----------- OPACITY ------------
--------------------------------
opacityCertainApps = hl.window_rule({
    name  = "opacity-for-certain-apps",
    match = { class = "thunar|Thunar|kitty|code|com.microsoft.VSCode|jetbrains.*" },

    opacity = 0.9,
})

-- Rules for tobimune.sh
tobimuneSpaceOpacityRule = hl.window_rule({
    name  = "opacity-tobimune",
    match = { class = "seycmd|seyclock|seylavat|seycava" },

    opacity = 0.8,
})

----------------------------------
----------- ANIMATIONS -----------
----------------------------------
-- Animation for Rofi
rofiAnimation = hl.layer_rule({
    name = "rofi-slide",
    match = { namespace = "rofi" },

    animation = "slide",
    blur = true,
    ignore_alpha = 0.5,
})
-- Animation for Waybar
waybarAnimation = hl.layer_rule({
    name = "waybar-fade",
    match = { namespace = "waybar" },

    animation = "fade",
})
-- Slide for Swaync
swayncAnimation = hl.layer_rule({
    name = "swaync-control-center",
    match = { namespace = "swaync-control-center" },

    animation = "slide right",
})

-------------------------------------------------
----------- Floating window for apps ------------
-------------------------------------------------
floatingCenter = hl.window_rule({
    name  = "floating-center",
    match = { class = "imv|mpv|org.gnome.Calculator" },

    float = true,
    size  = "1280 720",
})

floatingApps = hl.window_rule({
    name  = "floating-apps",
    match = { title = "Picture-in-Picture" },

    float = true,
})

-- Browser popups like save, etc. should usually be floating
floatingXdgPortal = hl.window_rule({
    name  = "xdg-desktop-portal-gtk",
    match = { class = "xdg-desktop-portal-gtk" },

    float = true,
    center = true,
    size  = "600 600",
})

---------------------------------
------- Tobimune Space Rules --------
---------------------------------

-- Rules for tobimune.sh | scrolling layout
hl.window_rule({
    name = "tobimune-left",
    match = { class = "seycmd" },
    scrolling_width = 0.6,
})

hl.window_rule({
    name = "tobimune-right",
    match = { class = "seyclock|seylavat|seycava" },
    scrolling_width = 0.4,
})

-- Taskbar style
hl.layer_rule({
    name = "tobimune-taskbar",
    match = { namespace = "taskbar.*" },

    blur = false,
    animation = "slide bottom",
})

-- Desktop icons disable animations
hl.layer_rule({
    name = "tobimune-desktop-icons",
    match = { namespace = "desktop-icons" },
    no_anim = true,
})

-- Desktop icons style - Rename
hl.window_rule({
    name = "tobimune-desktop-icons",
    match = { namespace = "desktop-icons" },
    match = { title = "Rename.*|Create.*" },

    float = true,
    size = "300 100",
})


---------------------------------------
---------- Turn on/off rules ----------
---------------------------------------
-- Hyprland useful rules, why not?
suppressMaximizeRule:set_enabled(true)
hyprlandRunRule:set_enabled(true)
fixXwaylandDrags:set_enabled(true)

codeSpecialWorkspace:set_enabled(true) -- VS Code in special workspace (SUPER + `)
fullscreenBorder:set_enabled(false) -- Red border for fullscreen windows

-- Scrolling layout rules
fullWidth_ScrollingLayout:set_enabled(true) -- Set width 100% for certain apps
specificWidth_ScrollingLayout:set_enabled(true) -- Set width 60% for certain apps

-- Opacity rules
opacityCertainApps:set_enabled(true) -- Specific apps opacity
tobimuneSpaceOpacityRule:set_enabled(true) -- tobimune.sh kitty opacity

-- Animation rules
rofiAnimation:set_enabled(true)
waybarAnimation:set_enabled(true)
swayncAnimation:set_enabled(true)

-- Floating window rules
floatingCenter:set_enabled(true) -- Floating Centered apps (mpv, imv, calculator)
floatingApps:set_enabled(true) -- Floating apps (pavucontrol)
floatingXdgPortal:set_enabled(true) -- Floating xdg-desktop-portal-gtk (save, open, etc.)