#     __                     _     ____   
#    / /_  __  ______  _____(_)___/ / /__ 
#   / __ \/ / / / __ \/ ___/ / __  / / _ \
#  / / / / /_/ / /_/ / /  / / /_/ / /  __/
# /_/ /_/\__, / .___/_/  /_/\__,_/_/\___/ 
#       /____/_/                          

# fallback timeout
$timeout_dim = 120
$timeout_lock = 150
$timeout_dpms = 180
$timeout_suspend = 300
$condition_retry_timeout = 30

# Include timeout
source = ~/hakucfg/config/hypridle.conf

general {
    lock_cmd = pidof hyprlock || ~/.local/bin/lock.sh
    before_sleep_cmd = loginctl lock-session && ~/.local/bin/dpms_handler.sh off
    after_sleep_cmd = ~/.local/bin/dpms_handler.sh on
}

# Set brightness
listener {
    timeout = $timeout_dim
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
    condition_cmd = ~/.local/bin/idle_inhibit.sh
    condition_retry = $condition_retry_timeout
}

# Lock screen
listener {
    timeout = $timeout_lock
    on-timeout = loginctl lock-session
    condition_cmd = ~/.local/bin/idle_inhibit.sh
    condition_retry = $condition_retry_timeout
}

# Turn off display (DPMS)
listener {
    timeout = $timeout_dpms
    on-timeout = ~/.local/bin/dpms_handler.sh off
    on-resume = ~/.local/bin/dpms_handler.sh on && sleep 0.5 && brightnessctl -r
    condition_cmd = ~/.local/bin/idle_inhibit.sh
    condition_retry = $condition_retry_timeout
}

# Put machine to Sleep
listener {
    timeout = $timeout_suspend
    on-timeout = systemctl suspend
    condition_cmd = ~/.local/bin/idle_inhibit.sh
    condition_retry = $condition_retry_timeout
}