#       __  ___                      
#      /  |/  /___ _____  ____ _____ 
#     / /|_/ / __ `/ __ \/ __ `/ __ \
#    / /  / / /_/ / / / / /_/ / /_/ /
#   /_/  /_/\__,_/_/ /_/\__, /\____/ 
#                      /____/        

# This is a mangowm custom configuration file (small config.conf actually :p)
# You can add keybindings, rules, and other configurations here.

# Why you should custom your config in there?
# Because for each update, my dotfiles will override your all custom configurations.

# After changes, please reload Mangowm by `SUPER + ALT + R` keybinding or restart

# See more in the Wiki: https://github.com/mangowm/mango/wiki

# Example:

# Set border width
borderpx=3

# Set border radius
border_radius=4

# Set Keybindings
# Warning: If base config has the same keybinding, mango will use both keybindings
# For example: my base config has SUPER+B for open firefox, and you set SUPER+B for open zen browser,
# Mango will open both firefox and zen browser when you press SUPER+B, you should remove firefox :(
# Btw example keybinding:
bind=SUPER,Return,spawn,kitty

# If you have issues with open default web in browser
# Set your default browser:
# bind=SUPER,B,spawn,your browser

# Set cursor size
cursor_size=24

