#     __   _ __  __       
#    / /__(_) /_/ /___  __
#   / //_/ / __/ __/ / / /
#  / ,< / / /_/ /_/ /_/ / 
# /_/|_/_/\__/\__/\__, /  
#                /____/   

include ~/.local/state/hakuspace/theme/kitty-style.conf
allow_remote_control yes
listen_on unix:/tmp/kitty

# FONT
#font_family already defined in kitty-style.conf
#font_size already defined in kitty-style.conf
bold_font        auto
italic_font      auto
bold_italic_font auto

# COLOR SCHEME
# Black
color0 #000000
color8 #282828

# Red
color1 #cc241d
color9 #fb4934

# Green
color2  #98971a
color10 #b8bb26

# Yellow
color3  #d79921
color11 #fabd2f

# Blue
color4  #458588
color12 #83a598

# Magenta
color5  #b16286
color13 #d3869b

# Cyan
color6  #689d6a
color14 #8ec07c

# White already defined in kitty-style.conf

# CONFIGURATION
background_opacity 0.9
window_margin_width 20
confirm_os_window_close 0

cursor_shape beam
cursor_shape_unfocused block
cursor_blink_interval 1
mouse_hide_wait 3.0
cursor_trail 2
cursor_trail_decay 0.1 0.4

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

scrollback_lines 5000
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+t new_tab_with_cwd

# Include opaque theme config feature
# include ~/.local/state/hakuspace/theme/opaque/kitty.conf

# Include custom config from hakucfg
include ~/hakucfg/config/kitty.conf