#     __                     _     ____   
#    / /_  __  ______  _____(_)___/ / /__ 
#   / __ \/ / / / __ \/ ___/ / __  / / _ \
#  / / / / /_/ / /_/ / /  / / /_/ / /  __/
# /_/ /_/\__, / .___/_/  /_/\__,_/_/\___/ 
#       /____/_/                          

# Custom timeouts for hypridle here
# Core hypridle.conf is still in ~/.config/hypr/hypridle.conf

# Timeout for dimming the screen (seconds)
$timeout_dim = 200

# Timeout for locking the screen
$timeout_lock = 230

# Timeout for turning off the display (DPMS)
$timeout_dpms = 300

# Timeout for putting the machine to sleep
$timeout_suspend = 360

# Condition retry timeout for idle_inhibit.sh
# More info: https://wiki.hypr.land/Hypr-Ecosystem/hypridle/#conditional-timeouts
$condition_retry_timeout = 30