#     __  __                 __           __  
#    / / / /_  ______  _____/ /___  _____/ /__
#   / /_/ / / / / __ \/ ___/ / __ \/ ___/ //_/
#  / __  / /_/ / /_/ / /  / / /_/ / /__/ ,<   
# /_/ /_/\__, / .___/_/  /_/\____/\___/_/|_|  
#       /____/_/                              

# Custom label for hyprlock here
# Core hyprlock.conf is still in ~/.config/hypr/hyprlock.conf (and more config files)

# Top label text
$top_label = Hi there, $USER

# Bottom label text
$bottom_label = Have a nice day!

# Input placeholder text
$input_placeholder = <i> Use Me ;) </i>