add_newline = true

format = '''
[╭─●](white)  $username@$hostname $directory $git_branch$git_status$git_state ●$fill● $cmd_duration $time
[╰─](white)$character$nix_shell '''

[fill]
symbol = '─'
style = 'bold dimmed white'

[character]
success_symbol = '[▶︎](bold white)'
error_symbol = '[✘](bold red)'

[time]
disabled = false
time_format = '%H:%M'
style = 'white'
format = '[󱑎 $time]($style)'

[username]
format = '[$user]($style)'
style_root = 'bold red'
style_user = 'bold white'
show_always = true

[hostname]
format = '[$ssh_symbol$hostname]($style)'
ssh_symbol = '󰌾 '
ssh_only = false
style = 'bold white'

[directory]
style = 'bold white'
format = '[| 󰝰  $path]($style)'
truncation_length = 4

[git_branch]
symbol = '󰊢'
style = 'blue'
format = ' [$symbol $branch]($style)'

[git_status]
style = 'yellow'
format = ' ([\[$all_status$ahead_behind\]]($style) )'

[git_state]
style = 'green'

[cmd_duration]
min_time = 2000
style = 'white'
format = '[󱎫 $duration]($style) 󰧄'

[nix_shell]
style = 'bold white'
symbol = ' '
format = 'via [$symbol$state( \($name\))]($style)  '