#     __   _ __  __       
#    / /__(_) /_/ /___  __
#   / //_/ / __/ __/ / / /
#  / ,< / / /_/ /_/ /_/ / 
# /_/|_/_/\__/\__/\__, /  
#                /____/   

# This is a custom configuration file for the Kitty terminal
# Core kitty.conf is still in ~/.config/kitty/kitty.conf

# Example:

#background_opacity 0.7